### ISSUE TITLE
Windows / VS Code Pipx Install Failure

### ISSUE THREAD

**Issue by mtkapp277** [petminion/petminion#1]
This could be just my local setup, but not sure how to proceed.

[cmd_2024-02-03_21.44.52_pip_errors.log](https://github.com/petminion/petminion/files/14155285/cmd_2024-02-03_21.44.52_pip_errors.log)

$ pipx install petminion
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\Michael\AppData\Local\pipx\pipx\Logs\cmd_2024-02-03_21.44.52_pip_errors.log

pip failed to build package:
    Pillow

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    The headers or library files could not be found for zlib,
    RequiredDependencyException: zlib

Error installing petminion.

**Comment by geeksville** [comment]
oh thanks!  I haven't spit out a 'real/uptodate' petminion package on pypi in a while.  I'll do that in the next couple of days and send you a note.

**Comment by geeksville** [comment]
Hi @mtkapp277 I think it is fixed now.  Can you retry?  If still broken please reopen this bug and attach a log?  I don't normally use windows but I fired this up in a VM and discovered that an extra install step is also needed (besides updating petminion for other fixes).

Also if you encounter other problems or have questions please open other issues or send me an email.  Things are still super 'rough' in here. ;-)

Details here: https://github.com/petminion/petminion/commit/053d265c35618404a3435d2752e362e7d6c70e17
